# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: ubuntu-latest

#variables:
#- group: setting_secret

steps:

- task: DownloadSecureFile@1
  name: settings_xml
  inputs:
    secureFile: 'settings.xml'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      #echo $(test)
      ls
      echo Hello, world!
      cat >settin.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                    https://maven.apache.org/xsd/settings-1.0.0.xsd">
        <servers>
          <server>
            <id>moh</id>
            <username>mohasinpathan005</username>
            <password>itest)</password>
          </server>
        </servers>
        </settings>
      EOF
      ls
      cat settings.xml
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    #publishJUnitResults: true
    #testResultsFiles: '**/surefire-reports/TEST-*.xml'
    
    options: '--settings $(settings_xml.secureFilePath)'
    goals: 'compile'
